Create Secret String

Secret strings are custom values encoded with unique repository information so that you may include sensative information inside your yaml file. These secret strings can be made public as their contents can only be decoded by Codecov backend and require information not presented to any end-user.

Validate Syntax

curl --data-binary @codecov.yml https://codecov.io/validate

Copy

No codecov.yml file found on master yet.

Already added one? Great! This message will be removed upon the next upload to master branch.
Codecov uses a yaml file for all team and repository settings

Using a yaml file give you more customization and transparency to Codecov operations.

Click above to redirect to GitHub and create your codecov.yml file.

Bold values are default.

codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"

    hipchat:
      default:
        url: null
        notify: no
        threshold: null
        branches: null
        card: yes
        only_pulls: null
        message: null

    gitter:
      default:
        url: null
        threshold: null
        branches: null
        message: null

    webhook:
      default:
        url: null
        threshold: null
        branches: null
        only_pulls: null

    irc:
      default:
        server: null
        branches: null
        threshold: null
        message: null

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default

Learn more about why we use a yaml file for team and project settings.

Please click on a yaml setting to review documentation.

Have a question? Feel free to ask our Support Team
© 2016 Codecov Terms Privacy Security
Pricing Support Docs Enterprise
